name: Security Scan (SAST, SCA & IaC)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    name: Security Scan Pipeline
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Step 1: Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # Step 2: Run Semgrep (SAST)
      # -------------------------------
      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/php"
          audit_on: "push"

      # -------------------------------
      # Step 3: Run tfsec (Terraform IaC Scan)
      # -------------------------------
      - name: Run tfsec (Terraform IaC Scan)
        uses: aquasecurity/tfsec-action@v1
        with:
          format: sarif
          output_file: tfsec-results.sarif

      # Upload results to GitHub Security Dashboard
      - name: Upload tfsec results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-results.sarif

      # -------------------------------
      # Step 4: Login to Docker Hub
      # -------------------------------
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # -------------------------------
      # Step 5: Build Docker image
      # -------------------------------
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest .

      # -------------------------------
      # Step 6: Run Trivy vulnerability scan (SCA)
      # -------------------------------
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          scanners: 'vuln,secret'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'

      # -------------------------------
      # Step 7: Upload Trivy results to GitHub Security Dashboard
      # -------------------------------
      - name: Upload Trivy scan results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # -------------------------------
      # Step 8: Evaluate CRITICAL vulnerabilities
      # -------------------------------
      - name: Evaluate vulnerability severity
        id: eval
        run: |
          critical=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy-results.sarif || echo 0)
          echo "Detected $critical critical vulnerabilities."
          echo "critical=$critical" >> $GITHUB_OUTPUT

      # -------------------------------
      # Step 9: Fail pipeline if CRITICAL vulnerabilities exist
      # -------------------------------
      - name: Fail pipeline on critical vulnerabilities
        if: ${{ steps.eval.outputs.critical != '0' }}
        run: |
          echo "CRITICAL VULNERABILITIES FOUND: Security scan failed. Check trivy-results.sarif."
          exit 1

      # -------------------------------
      # Step 10: Push Docker image (only if scan passes)
      # -------------------------------
      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest
