name: Security Scan (SAST & SCA)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    name: Security Scan Pipeline
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Step 1: Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # Step 2: Configure AWS credentials
      # -------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # -------------------------------
      # Step 3: Semgrep (SAST)
      # -------------------------------
      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/php"
          audit_on: "push"

      # -------------------------------
      # Step 4: Login to Docker Hub
      # -------------------------------
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # -------------------------------
      # Step 5: Build Docker image
      # -------------------------------
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest .

      # -------------------------------
      # Step 7: Run Trivy Scan (SCA)
      # -------------------------------
      - name: Scan image for vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest
          format: 'table'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true     # Skip CVEs that have no official patch
          exit-code: '0'           # Don’t fail the pipeline; report only
          vuln-type: 'os,library'  # Include both OS & dependencies
          scanners: 'vuln,secret'  # Scan for both vulnerabilities and secrets

      # -------------------------------
      # Step 7: Push Docker image
      # -------------------------------
      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest
