name: Security Scan (SAST & SCA)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    name: Security Scan Pipeline
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Step 1: Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # Step 2: Configure AWS credentials
      # -------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # -------------------------------
      # Step 3: Semgrep (SAST)
      # -------------------------------
      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/php"
          audit_on: "push"

      # -------------------------------
      # Step 4: Login to Docker Hub
      # -------------------------------
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # -------------------------------
      # Step 5: Build Docker image
      # -------------------------------
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest .

      # -------------------------------
      # Step 7: Run Trivy Scan (SCA) - Conditional Enforcement
      # -------------------------------
      - name: Scan image for vulnerabilities (Trivy)
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest
          format: 'json'                     
          output: trivy-report.json          
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true               
          exit-code: '0'                     
          vuln-type: 'os,library'
          scanners: 'vuln,secret'

      # -------------------------------
      # Step 8: Parse Trivy Results
      # -------------------------------
      - name: Evaluate vulnerability severity
        id: eval
        run: |
          critical=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy-report.json)
          echo "Detected $critical critical vulnerabilities."
          echo "critical=$critical" >> $GITHUB_OUTPUT

      # -------------------------------
      # Step 9: Fail if CRITICAL CVEs exist
      # -------------------------------
      - name: Fail pipeline on critical vulnerabilities
        if: ${{ steps.eval.outputs.critical != '0' }}
        run: |
          echo "WARNING - CRITICAL VULNERABILITIES FOUND : Security scan failed, please check trivy-report.json."
          exit 1

      # -------------------------------
      # Step 10: Upload report as artifact
      # -------------------------------
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      # -------------------------------
      # Step 7: Push Docker image
      # -------------------------------
      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/research-app:latest
